/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    people: PersonAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    people: Person;
    'membership-plans': MembershipPlan;
    media: Media;
    classes: Class;
    'class-instances': ClassInstance;
    bookings: Booking;
    payments: Payment;
    'firing-requests': FiringRequest;
    'shelf-tags': ShelfTag;
    shelves: Shelf;
    coupons: Coupon;
    newsletters: Newsletter;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'class-instances': {
      roster: 'bookings';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    'membership-plans': MembershipPlansSelect<false> | MembershipPlansSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    classes: ClassesSelect<false> | ClassesSelect<true>;
    'class-instances': ClassInstancesSelect<false> | ClassInstancesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'firing-requests': FiringRequestsSelect<false> | FiringRequestsSelect<true>;
    'shelf-tags': ShelfTagsSelect<false> | ShelfTagsSelect<true>;
    shelves: ShelvesSelect<false> | ShelvesSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'membership-page': MembershipPage;
    'firings-page': FiringsPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'membership-page': MembershipPageSelect<false> | MembershipPageSelect<true>;
    'firings-page': FiringsPageSelect<false> | FiringsPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Person;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PersonAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles?: ('admin' | 'editor' | 'instructor')[] | null;
  /**
   * Shown on the Meet the Staff page
   */
  title?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  showOnStaffPage?: boolean | null;
  /**
   * Sort order on the Staff page
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Accessibility description (optional)
   */
  alt?: string | null;
  /**
   * Show this image in the public gallery. In a bulk upload, set it once and use “apply to all”.
   */
  includeInGallery?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  /**
   * Assign a plan to make this person a member; leave empty for a non-member contact.
   */
  plan?: (number | null) | MembershipPlan;
  phone?: string | null;
  status?: ('none' | 'active' | 'past_due' | 'paused' | 'cancelled') | null;
  joinedDate?: string | null;
  shelf?: (number | null) | Shelf;
  notes?: string | null;
  squareCustomerId?: string | null;
  squareSubscriptionId?: string | null;
  subscriptionStatus?: string | null;
  lastPaymentDate?: string | null;
  lastPaymentStatus?: string | null;
  cancelTokenHash?: string | null;
  cancelTokenExpiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'people';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-plans".
 */
export interface MembershipPlan {
  id: number;
  name: string;
  kind: 'square' | 'free';
  /**
   * Synced from Square; empty for Free plans.
   */
  squarePlanVariationId?: string | null;
  /**
   * Synced from Square.
   */
  priceCents?: number | null;
  /**
   * e.g. MONTHLY (synced).
   */
  cadence?: string | null;
  /**
   * Square plans removed from Square are set inactive by sync.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Filter by "Assigned Member → exists: No" to see currently-unassigned shelves.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shelves".
 */
export interface Shelf {
  id: number;
  /**
   * Free-form shelf number/name, e.g. "B-12".
   */
  name: string;
  tag?: (number | null) | ShelfTag;
  /**
   * Set automatically from the member's page.
   */
  assignedMember?: (number | null) | Person;
  sortKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shelf-tags".
 */
export interface ShelfTag {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes".
 */
export interface Class {
  id: number;
  title: string;
  /**
   * Auto-filled from title; edit to override
   */
  slug?: string | null;
  skillLevel?: string | null;
  description?: string | null;
  /**
   * Title image; default for all instances
   */
  image?: (number | null) | Media;
  /**
   * Price in dollars, e.g. 220 for $220.00. Instances inherit this unless overridden.
   */
  defaultPriceCents: number;
  /**
   * Instances inherit this unless overridden.
   */
  defaultCapacity: number;
  /**
   * How many sessions a run of this class includes. Instances inherit this (and fill in their end date from it) unless overridden.
   */
  defaultNumberOfClasses?: number | null;
  status?: ('active' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class-instances".
 */
export interface ClassInstance {
  id: number;
  class: number | Class;
  /**
   * Auto-filled from the class — edit to tell concurrent runs apart, e.g. add “ — Tuesday Nights”.
   */
  label?: string | null;
  instructor: number | User;
  /**
   * First (or only) meeting date
   */
  startDate: string;
  /**
   * 24-hour HH:MM, e.g. 18:00
   */
  startTime: string;
  /**
   * 24-hour HH:MM, e.g. 20:00
   */
  endTime: string;
  /**
   * Which days the class meets (multi-week courses).
   */
  daysOfWeek?: ('SU' | 'MO' | 'TU' | 'WE' | 'TH' | 'FR' | 'SA')[] | null;
  /**
   * For a multi-week course, how many sessions it runs (inherited from the class). Fills in the end date automatically — set this OR an end date, not both.
   */
  numberOfClasses?: number | null;
  /**
   * Last meeting date. Leave blank for a single-day class, or set "Number of classes" instead and this fills in automatically.
   */
  endDate?: string | null;
  /**
   * Dates to exclude (e.g. holidays).
   */
  skipDates?:
    | {
        date: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Defaults from the class if left blank.
   */
  capacity?: number | null;
  /**
   * Defaults from the class if left blank. Price in dollars.
   */
  priceCents?: number | null;
  /**
   * Optional; falls back to the class image.
   */
  image?: (number | null) | Media;
  /**
   * Optional; falls back to the studio address.
   */
  location?: string | null;
  /**
   * Only Published instances appear on the website.
   */
  status?: ('draft' | 'published' | 'cancelled' | 'completed') | null;
  /**
   * Everyone enrolled in this instance.
   */
  roster?: {
    docs?: (number | Booking)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  classInstance: number | ClassInstance;
  /**
   * The person who made this booking.
   */
  person?: (number | null) | Person;
  customerName: string;
  customerEmail: string;
  customerPhone?: string | null;
  status: 'pending' | 'paid' | 'cancelled' | 'refunded';
  amountCents: number;
  /**
   * Coupon discount applied. Original price = amount + discount.
   */
  discountCents?: number | null;
  coupon?: (number | null) | Coupon;
  squarePaymentId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  /**
   * Customers enter this at checkout. Stored uppercase; entry is case-insensitive.
   */
  code: string;
  discountType: 'percent' | 'fixed';
  /**
   * 1–100
   */
  percentOff?: number | null;
  amountOffCents?: number | null;
  appliesTo?: ('all' | 'class' | 'firing') | null;
  /**
   * Covers every session of this class.
   */
  class?: (number | null) | Class;
  active?: boolean | null;
  /**
   * Optional — code stops working after this date.
   */
  expiresAt?: string | null;
  /**
   * Optional — total uses allowed across all customers.
   */
  maxRedemptions?: number | null;
  /**
   * Each email can use this code once.
   */
  onePerCustomer?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  type: 'booking' | 'membership' | 'firing';
  /**
   * Set for membership payments
   */
  member?: (number | null) | Person;
  /**
   * Set for class booking payments
   */
  booking?: (number | null) | Booking;
  /**
   * Set for firing payments
   */
  firingRequest?: (number | null) | FiringRequest;
  amountCents: number;
  /**
   * Square payment or invoice id (empty for $0 coupon bookings).
   */
  squareId?: string | null;
  /**
   * Mirrors the raw Square payment/invoice status (e.g. COMPLETED).
   */
  status: string;
  paidAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "firing-requests".
 */
export interface FiringRequest {
  id: number;
  name: string;
  /**
   * The person who requested this firing.
   */
  person?: (number | null) | Person;
  email: string;
  phone?: string | null;
  description: string;
  /**
   * Customer notes
   */
  notes?: string | null;
  /**
   * Number of half-shelves reserved (11″×22″×6″ each).
   */
  halfShelves: number;
  amountCents: number;
  /**
   * Coupon discount applied. Original price = amount + discount.
   */
  discountCents?: number | null;
  coupon?: (number | null) | Coupon;
  squarePaymentId?: string | null;
  /**
   * Customer confirmed all pieces are stoneware (cone 10 safe).
   */
  stonewareConfirmed: boolean;
  /**
   * Up to 5 photos of the work being fired.
   */
  photos?: (number | Media)[] | null;
  /**
   * Workflow: Paid → Dropped off → Completed. Marking Completed emails the customer that their pieces are ready for pickup.
   */
  status?: ('pending' | 'paid' | 'dropped_off' | 'completed' | 'cancelled' | 'refunded') | null;
  paidAt?: string | null;
  /**
   * Set when marked Completed. Attached photos are auto-deleted 2 weeks after this.
   */
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Compose a newsletter, proof it with “Send test to me”, then send it to the mailing list.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: number;
  /**
   * The email subject line.
   */
  subject: string;
  /**
   * Headings, text, links, lists, and images all render inside the studio email template.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status?: ('draft' | 'sent') | null;
  sentAt?: string | null;
  kitBroadcastId?: string | null;
  recipientCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'membership-plans';
        value: number | MembershipPlan;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'classes';
        value: number | Class;
      } | null)
    | ({
        relationTo: 'class-instances';
        value: number | ClassInstance;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'firing-requests';
        value: number | FiringRequest;
      } | null)
    | ({
        relationTo: 'shelf-tags';
        value: number | ShelfTag;
      } | null)
    | ({
        relationTo: 'shelves';
        value: number | Shelf;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: number | Newsletter;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'people';
        value: number | Person;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'people';
        value: number | Person;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  title?: T;
  bio?: T;
  photo?: T;
  showOnStaffPage?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  plan?: T;
  phone?: T;
  status?: T;
  joinedDate?: T;
  shelf?: T;
  notes?: T;
  squareCustomerId?: T;
  squareSubscriptionId?: T;
  subscriptionStatus?: T;
  lastPaymentDate?: T;
  lastPaymentStatus?: T;
  cancelTokenHash?: T;
  cancelTokenExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-plans_select".
 */
export interface MembershipPlansSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  squarePlanVariationId?: T;
  priceCents?: T;
  cadence?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  includeInGallery?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes_select".
 */
export interface ClassesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  skillLevel?: T;
  description?: T;
  image?: T;
  defaultPriceCents?: T;
  defaultCapacity?: T;
  defaultNumberOfClasses?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class-instances_select".
 */
export interface ClassInstancesSelect<T extends boolean = true> {
  class?: T;
  label?: T;
  instructor?: T;
  startDate?: T;
  startTime?: T;
  endTime?: T;
  daysOfWeek?: T;
  numberOfClasses?: T;
  endDate?: T;
  skipDates?:
    | T
    | {
        date?: T;
        id?: T;
      };
  capacity?: T;
  priceCents?: T;
  image?: T;
  location?: T;
  status?: T;
  roster?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  classInstance?: T;
  person?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  status?: T;
  amountCents?: T;
  discountCents?: T;
  coupon?: T;
  squarePaymentId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  type?: T;
  member?: T;
  booking?: T;
  firingRequest?: T;
  amountCents?: T;
  squareId?: T;
  status?: T;
  paidAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "firing-requests_select".
 */
export interface FiringRequestsSelect<T extends boolean = true> {
  name?: T;
  person?: T;
  email?: T;
  phone?: T;
  description?: T;
  notes?: T;
  halfShelves?: T;
  amountCents?: T;
  discountCents?: T;
  coupon?: T;
  squarePaymentId?: T;
  stonewareConfirmed?: T;
  photos?: T;
  status?: T;
  paidAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shelf-tags_select".
 */
export interface ShelfTagsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shelves_select".
 */
export interface ShelvesSelect<T extends boolean = true> {
  name?: T;
  tag?: T;
  assignedMember?: T;
  sortKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  discountType?: T;
  percentOff?: T;
  amountOffCents?: T;
  appliesTo?: T;
  class?: T;
  active?: T;
  expiresAt?: T;
  maxRedemptions?: T;
  onePerCustomer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  subject?: T;
  body?: T;
  status?: T;
  sentAt?: T;
  kitBroadcastId?: T;
  recipientCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  studioName: string;
  phone?: string | null;
  email?: string | null;
  addressLine?: string | null;
  hours?:
    | {
        days?: string | null;
        time?: string | null;
        id?: string | null;
      }[]
    | null;
  socials?:
    | {
        platform?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  /**
   * Browser tab icon for the public site. Use a square image — a .png, .svg, or .ico works best.
   */
  favicon?: (number | null) | Media;
  /**
   * Show “Newsletter” in the site menu instead of the “Classes” link. The “Book a class” button is unaffected.
   */
  newsletterInNav?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroKicker?: string | null;
  heroHeadline: string;
  heroSubtext?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Images for the three “What we offer” cards at the top of the homepage. Each card is independent — if left blank, it falls back to a story-section or gallery image.
   */
  visitCardImage?: (number | null) | Media;
  classCardImage?: (number | null) | Media;
  memberCardImage?: (number | null) | Media;
  sections?:
    | {
        heading: string;
        body: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  gallery?: (number | Media)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-page".
 */
export interface MembershipPage {
  id: number;
  headline: string;
  intro?: string | null;
  priceLabel: string;
  benefits?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "firings-page".
 */
export interface FiringsPage {
  id: number;
  headline: string;
  intro?: string | null;
  /**
   * Shown under the intro — e.g. a photo of the kiln or fired work.
   */
  image?: (number | null) | Media;
  steps?:
    | {
        step: string;
        id?: string | null;
      }[]
    | null;
  pricingNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  studioName?: T;
  phone?: T;
  email?: T;
  addressLine?: T;
  hours?:
    | T
    | {
        days?: T;
        time?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  logo?: T;
  favicon?: T;
  newsletterInNav?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroKicker?: T;
  heroHeadline?: T;
  heroSubtext?: T;
  heroImage?: T;
  visitCardImage?: T;
  classCardImage?: T;
  memberCardImage?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        image?: T;
        id?: T;
      };
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-page_select".
 */
export interface MembershipPageSelect<T extends boolean = true> {
  headline?: T;
  intro?: T;
  priceLabel?: T;
  benefits?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "firings-page_select".
 */
export interface FiringsPageSelect<T extends boolean = true> {
  headline?: T;
  intro?: T;
  image?: T;
  steps?:
    | T
    | {
        step?: T;
        id?: T;
      };
  pricingNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}